#!/usr/bin/env bun
/**
 * fetch-buildings.ts
 *
 * Build-time script that queries OpenStreetMap via Overpass API for real
 * building footprints with height data in each city's skyline district.
 *
 * Outputs typed BuildingSpec[] modules into src/data/buildings/{cityId}.ts.
 * These replace the randomly generated filler at runtime.
 *
 * Usage:
 *   bun run scripts/fetch-buildings.ts
 *
 * Overpass is free, open, and requires no API key.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = join(__dirname, '..', 'src', 'data', 'buildings')
const OVERPASS_URL = 'https://overpass-api.de/api/interpreter'

interface OsmElement {
  type: 'way' | 'relation' | 'node'
  id: number
  tags?: Record<string, string>
  center?: { lat: number; lon: number }
  lat?: number
  lon?: number
}

interface RawSpec {
  id: string
  name: string
  lat: number
  lng: number
  height: number
  width: number
  depth: number
  landmark: false
}

interface CityTarget {
  id: string
  lat: number
  lng: number
  radius: number
}

const CITIES: CityTarget[] = [
  { id: 'seoul', lat: 37.5125, lng: 127.1005, radius: 1400 },
  { id: 'new-york', lat: 40.7549, lng: -73.984, radius: 1400 },
  { id: 'dubai', lat: 25.195, lng: 55.275, radius: 1400 },
]

function buildQuery(lat: number, lng: number, radius: number): string {
  return `[out:json][timeout:30];
(
  way["building"]["height"](around:${radius},${lat},${lng});
  way["building"]["building:levels"](around:${radius},${lat},${lng});
);
out center;`
}

function parseHeightInMeters(tags?: Record<string, string>): number | null {
  if (!tags) return null

  const raw = tags.height ?? tags['building:height']
  if (raw) {
    const cleaned = raw.replace(/^[~≈]/, '').trim()
    const match = cleaned.match(/^([\d.]+)\s*(m|ft|feet|')?$/i)
    if (match) {
      let h = Number.parseFloat(match[1])
      if (Number.isNaN(h) || h <= 0 || h > 999) return null
      const unit = (match[2] ?? '').toLowerCase()
      if (unit === 'ft' || unit === 'feet' || unit === "'") h *= 0.3048
      return Math.round(h)
    }
  }

  const levels = tags['building:levels']
  if (levels) {
    const l = Number.parseFloat(levels)
    if (!Number.isNaN(l) && l > 0 && l < 200) return Math.round(l * 3.5)
  }

  return null
}

function getCenter(el: OsmElement): { lat: number; lng: number } | null {
  if (el.center) return { lat: el.center.lat, lng: el.center.lon }
  if (el.lat !== undefined && el.lon !== undefined) return { lat: el.lat, lng: el.lon }
  return null
}

function deterministicSizes(id: number): [width: number, depth: number] {
  const wSeed = ((id * 16807) % 2147483647) / 2147483647
  const dSeed = ((id * 48271) % 2147483647) / 2147483647
  return [Math.round(15 + 50 * Math.abs(wSeed)), Math.round(15 + 50 * Math.abs(dSeed))]
}

function encodeOverpassQuery(query: string): string {
  return encodeURIComponent(query).replace(/[()!*']/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase())
}

async function fetchCity(city: CityTarget): Promise<RawSpec[]> {
  const query = buildQuery(city.lat, city.lng, city.radius)

  const resp = await fetch(`${OVERPASS_URL}?data=${encodeOverpassQuery(query)}`, {
    headers: {
      'User-Agent': 'skyline-demo/0.1 (Overpass build-time fetcher; +https://github.com/anomalyco/skyline-demo)',
      Accept: 'application/json',
    },
    signal: AbortSignal.timeout(35_000),
  })

  if (!resp.ok) throw new Error(`HTTP ${resp.status} — ${resp.statusText}`)

  const data: { elements?: OsmElement[] } = await resp.json()
  const elements = data.elements ?? []

  const specs: RawSpec[] = []

  for (const el of elements) {
    const center = getCenter(el)
    if (!center) continue
    const height = parseHeightInMeters(el.tags)
    if (!height) continue

    const lat = Math.round(center.lat * 1e7) / 1e7
    const lng = Math.round(center.lng * 1e7) / 1e7
    const [width, depth] = deterministicSizes(el.id)

    specs.push({
      id: `osm-${el.type}-${el.id}`,
      name: el.tags?.name ?? '',
      lat,
      lng,
      height,
      width,
      depth,
      landmark: false,
    })
  }

  specs.sort((a, b) => b.height - a.height)
  return specs.slice(0, 1000)
}

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms))
}

async function main() {
  console.log('── Fetching real building data from Overpass API ──\n')

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })

  let total = 0

  for (const city of CITIES) {
    process.stdout.write(`  ${city.id} ... `)
    try {
      const buildings = await fetchCity(city)
      const content = `// Auto‑generated by scripts/fetch-buildings.ts — do not edit manually
import type { BuildingSpec } from '@/lib/skyline'

export const BUILDINGS: BuildingSpec[] = ${JSON.stringify(buildings, null, 2)}
`
      writeFileSync(join(OUT_DIR, `${city.id}.ts`), content, 'utf-8')
      console.log(`${buildings.length} buildings`)
      total += buildings.length
    } catch (err) {
      console.log(`FAILED — ${err}`)
      writeFileSync(
        join(OUT_DIR, `${city.id}.ts`),
        `// Overpass fetch failed for ${city.id}: ${err}
import type { BuildingSpec } from '@/lib/skyline'
export const BUILDINGS: BuildingSpec[] = []
`,
        'utf-8',
      )
    }
    await delay(1000)
  }

  console.log(`\n  Total: ${total} buildings across ${CITIES.length} cities`)
}

main().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
